modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL = "https://github.com/manmaed/petrock/issues"
[[mods]] #mandatory
modId="petrock" #mandatory
version = "${file.jarVersion}" #mandatory
displayName="PetRock" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/manmaed/petrock/main/update.json"
authors = "manmaed" #optional
description='''
A Mod that adds PetRocks!'''
[[dependencies.petrock]]
modId="forge"
mandatory=true
versionRange="[47.0.3,)"
ordering="NONE"
side="BOTH"